name: CI Build

on:
  push:
    branches: [ v1.0.0_fixes ]
    tags:
    - '*'
  pull_request:
    branches: [ v1.0.0_fixes ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - # Ubuntu 20.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: x86_64
          toolchainfile: ""
        - # Ubuntu 22.04 x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: x86_64
          toolchainfile: ""
        - # Windows x86
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: windows
          distribution-version: ""
          cpu-architecture: x86
          toolchainfile: "-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchainfiles/toolchain_windows_32.cmake"
        - # Windows x86_64
          image: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
          distribution-id: windows
          distribution-version: ""
          cpu-architecture: x86_64
          toolchainfile: "-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchainfiles/toolchain_windows_64.cmake"
    container: ${{ matrix.platform.image }}
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Configure
      run: mkdir build && cd build && cmake ${{ matrix.platform.toolchainfile }} ..
    - name: Build
      run: cd build && make && make package
    - name: Test
      run: cd build && make test
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: build/repository
